### ISSUE TITLE
Unable to resolve module Dimensions

### ISSUE THREAD

**Issue by Xabadu** [peter4k/React-Native-FMPicker#3] opened 2015-11-27 01:17 UTC
Hi,

Kudos for the work here, great component. Just had a little issue with the Dimensions module on this line:

```
var SCREEN_WIDTH = require('Dimensions').get('window').width;
```

Fixed it by deconstructing with the React object instead of using require, in case anyone runs into the same problem.

Do you know if it still works for you with the original code? If it doesn't, can I send a PR with the proposed change?

Thanks!

**Comment by peter4k** [comment] 2015-11-27 06:30
Hi, 
Thanks for reporting this issue.
I have not encountered this error in my projects. 
I will definitely change it to React object, can you let me know what version of node and react-native are you using, so I can reproduce the bug.

**Comment by Xabadu** [comment] 2015-11-27 11:00
Hey, thanks for the reply.

I'm using node 4.2.1 and react-native 0.14.2.

Cheers!

**Comment by nicoecheza** [comment] 2015-11-30 19:42
We are also having this problem. We solved it just requiring the Dimensions module from React and changed it in the index.js on the react-native-fm-picker module, since this is the recommended way since react-native 0.14.

Do you want me to create a pull request for this one?

**Comment by peter4k** [comment] 2015-11-30 21:14
Fixed in 0.0.3

**Closed as completed by peter4k** 2015-11-30 21:14 UTC

**Comment by peter4k** [comment] 2015-11-30 21:15
@nicoecheza Thanks for the suggestion. I have fixed this issue by exactly what you suggested.

**Comment by nicoecheza** [comment] 2015-12-01 12:43
nice! thanks :dancer:
